//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyProduct("NLog.Mongo")]
[assembly: System.Reflection.AssemblyCompany("LoreSoft")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © 2015 LoreSoft")]
[assembly: System.Reflection.AssemblyConfiguration("Release")]
[assembly: System.Reflection.AssemblyVersion("3.2.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("3.2.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("3.2.0.0")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]



internal sealed partial class ThisAssembly {
    
    internal const string AssemblyProduct = "NLog.Mongo";
    
    internal const string AssemblyCompany = "LoreSoft";
    
    internal const string AssemblyCopyright = "Copyright © 2015 LoreSoft";
    
    internal const string AssemblyConfiguration = "Release";
    
    internal const string AssemblyVersion = "3.2.0.0";
    
    internal const string AssemblyFileVersion = "3.2.0.0";
    
    internal const string AssemblyInformationalVersion = "3.2.0.0";
    
    private ThisAssembly() {
    }
}
